### PR TITLE
Fixes for Vietnamese translation

### PR DESCRIPTION
**Pull request by MrN83**
NOVAglow and I have collaborated to improve the Vietnamese translation. This includes completing some untranslated parts, as well as improving on previous translated parts. I have proof-read the work as well.

This should be good to go live.

Thanks!

### CODE REVIEW

**Comment by ncase** [comment]
Awesome! Thank you all so much for the hard work you put into this, I'm excited to see it's finally done! :)

**Comment by MrN83** [comment]
Thank you! I'm actually using this in my teaching (I'm a Maths/CompSci teacher). I'm planning to incorporate the game theory stuff as well. I was already drawing cartoons and stuff to illustrate these concepts but your work makes things so much more attractive!

I'm really hoping to promote "crowds" to more Vietnamese students as well. I notice that the link: https://ncase.me/crowds/vi.html still brings up the old version. When will the new translation be available to the general public?

Thanks!

**Comment by ncase** [comment]
Hi sorry @MrN83 ! I was busy and forgot to actually update the `gh-pages` branch, which is where the page is actually hosted! (it was only committed to the `master` branch)

I've just updated the `gh-pages` branch – it should be updated by now! (If not, clear cache & refresh page) [https://ncase.me/crowds???](https://ncase.me/crowds???)

I'm really honored to hear you're showing my work in your Maths/CompSci class. Hope your students like it! :)

**Comment by MrN83** [comment]
Thank you! It's all good now 👍.

My students loved it and so did many other teachers at school. Your work makes very complex and profound ideas accessible. I'm hoping to show my students your game theory simulation next. I made an ALife simulation based on game theory for my undergrad degree years ago to study racism, and such ideas have been a lasting influence in my life since. Keep up the good work! :)

**Comment by ncase** [comment]
That's awesome! I'm glad my work could be helpful :) Thank you!

**Pull request merged**
