### PR TITLE
Added Russian translation

### PR DESCRIPTION
**Pull request by toby3d**
Hello from [another translation](https://github.com/notdotteam/trust/)! :wave: 
As always - I will keep the translation up to date and to correct errors, if any detected.

### CODE REVIEW

**Comment by ncase** [comment]
Awesome! Thank you so much @toby3d ! :)

**Comment by toby3d** [comment]
@ncase I will open an additional PR when my friends process the remaining mistakes and shortcomings in the translation. Thanks again!

**Comment by toby3d** [comment]
default
Also, change building GitHub Pages on `master` branch for avoid duplicating source to `gh-pages` branch.

**Comment by ncase** [comment]
Yup, that is indeed what I _should_ do, but I am terrible at git, and want to keep two separate branches – "master" is my development branch, "gh-pages" is production -- because I know I'll screw something up eventually :P

**Pull request merged**
